version: '3'

services:
  app:
    image: nextcloud
    environment:
      - REDIS_HOST=redis
    volumes:
      - app:/var/www/html
    links:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres:9
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  app:
    external: false
  db:
    external: false
